export const AUTH_LOGIN_lOADING = "AUTH_LOGIN_lOADING";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_REGISTER_LOADING = "AUTH_REGISTER_LOADING";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL";
export const GOOGLE_LOGIN = "GOOGLE_LOGIN";
export const LOGOUT = "LOGOUT";
